# Name:- Arjun Chauhan
# Insragram Handle:- @rockstarjun.py

from turtle import *
t=Turtle()
win=Screen()
win.title("Letter A")
win.bgcolor("black")
t.speed(10)
t.penup()
t.setposition(-250,-250)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(100)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.setposition(-150,-150)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(80)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.setposition(-70,-70)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(60)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(50)
    t.left(102.856)
t.end_fill()
t.penup()
t.setposition(250,-250)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(100)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.setposition(150,-150)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(80)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.setposition(70,-70)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(60)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.pendown()
t.penup()
t.setposition(250,250)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(100)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.setposition(150,150)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(80)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.setposition(70,70)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(60)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.pendown()
t.penup()
t.setposition(-250,250)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(100)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.setposition(-150,150)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(80)
    t.left(102.856)
t.end_fill()
print(t.position())
t.penup()
t.setposition(0,0)
t.setposition(-70,70)
t.pendown()
t.color("dark blue","dark violet")
t.begin_fill()
for i in range(7):
    t.forward(60)
    t.left(102.856)
t.end_fill()
print(t.position())
done()